version: '2'
services:
  portainer:
    image: 'portainer/portainer:latest'
#    command: portainer --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key
    container_name: ui
    restart: always    
    ports:
      - 9001:9000
    volumes:
      - '/srv/portainer-persistence/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
